services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - APP_PORT=3001
