apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-payment-general-settings
data:
  NODE_ENV: "development"
  APP_NAME: "tech-challenge-payment"
  APP_PORT: "3003"
  APP_VERSION: "1.0.0"
  APP_DOCUMENTATION_ENDPOINT: "docs"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "${{ secrets.POSTGRES_HOST }}"
