apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-payment-general-settings
data:
  NODE_ENV: "development"
  APP_NAME: "tech-challenge-payment"
  APP_PORT: "3003"
  APP_VERSION: "1.0.0"
  APP_DOCUMENTATION_ENDPOINT: "docs"
  MERCADO_PAGO_PAYMENT_URL: "https://api.mercadopago.com/instore/orders/qr/seller/collectors/$USERID/pos/$EXTERNALPOS/qrs"
  MERCADO_PAGO_NOTIFICATION_URL: "https://8a40-179-235-122-235.ngrok-free.app/api/payment/payment-notification"
  ORDER_QUEUE_NAME: "order-created-queue.fifo"
  ORDER_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/528038094654/order-created-queue.fifo"
  PAYMENT_QUEUE_NAME: "payment-status-updated-queue.fifo"
  PAYMENT_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/528038094654/payment-status-updated-queue.fifo"
