apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-payment-deployment
spec:
  selector:
    matchLabels:
      app: tech-challenge-payment-deployment
  template:
    metadata:
      labels:
        app: tech-challenge-payment-deployment
    spec:
      containers:
      - name: tech-challenge-payment
        image:  diname/tech-challenge-payment:latest
        envFrom:
        - configMapRef:
            name: tech-challenge-payment-general-settings
        - secretRef:
            name: tech-challenge-payment-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 180
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 250m
            memory: 100Mi
          limits:
            memory: 400Mi
            cpu: 500m # 1/2 núcleo
        ports:
        - containerPort: 3003
